import { Sparkles } from "lucide-react"

import { Card, CardContent } from "@/components/ui/card"

type InsightCardProps = {
  modelName: string
  dataset: string
  validationMape: string
  forecastHorizon: string
  generatedAt: string
}

export function InsightCard({ modelName, dataset, validationMape, forecastHorizon, generatedAt }: InsightCardProps) {
  return (
    <Card className="animate-enter min-h-[300px] border-[#2563EB]/20 bg-[#2563EB] text-white shadow-[0_26px_70px_rgba(37,99,235,0.22)]">
      <CardContent className="flex h-full flex-col justify-between">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="size-4 text-white" />
            <p className="text-[11px] font-bold uppercase tracking-[0.16em] text-white/72">AI Model Insights</p>
          </div>
          <p className="mt-5 max-w-xl text-[15px] font-medium leading-7 text-white">
            Forecasts are generated by {modelName}
            {dataset === "Unavailable" ? "." : ` using ${dataset}.`} Latest generation: {generatedAt}.
          </p>
        </div>
        <div className="mt-8 grid grid-cols-2 gap-3">
          <div className="rounded-[15px] bg-white/12 p-3.5 ring-1 ring-white/12">
            <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-white/64">Validation MAPE</p>
            <p className="mt-2 tabular-nums text-[20px] font-semibold text-white">{validationMape}</p>
          </div>
          <div className="rounded-[15px] bg-white/12 p-3.5 ring-1 ring-white/12">
            <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-white/64">Forecast Horizon</p>
            <p className="mt-2 tabular-nums text-[20px] font-semibold text-white">{forecastHorizon}</p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
